import flet as ft

# ==========================================================
# LANGUAGE DICTIONARY
# ==========================================================

languages = {

    # ======================================================
    # ENGLISH
    # ======================================================

    "English": {

        # ---------------- Login ----------------

        "login": "Login",
        "login_as": "Login As",
        "shopkeeper": "Shopkeeper",
        "employee": "Employee",

        "username": "Username",
        "password": "Password",

        "remember_me": "Remember Me",
        "forgot_password": "Forgot Password?",

        "welcome": "Welcome",
        "welcome_back": "Welcome Back",

        "invalid_login": "Invalid Username or Password",

        # ---------------- Language ----------------

        "select_language": "Select Language",

        "continue": "Continue",

        # ---------------- Header ----------------

        "app_name": "Udhaar Management System",

        "search": "Search Customer, Payment, Transaction...",

        "dark_mode": "Dark Mode",

        # ---------------- Sidebar ----------------

        "dashboard": "Dashboard",

        "customers": "Customers",

        "add_customer": "Add Customer",

        "view_customers": "View Customers",

        "update_customer": "Update Customer",

        "customer_performance": "Customer Performance",

        "credit_items": "Credit Items",

        "add_credit_item": "Add Credit Item",

        "view_credit_items": "View Credit Items",

        "update_credit_item": "Update Credit Item",

        "payments": "Payments",

        "add_payment": "Add Payment",

        "view_payments": "View Payments",

        "update_payment": "Update Payment",

        "credit_transactions": "Credit Transactions",

        "add_transaction": "Add Transaction",

        "view_transactions": "View Transactions",

        "update_transaction": "Update Transaction",

        "outstanding_balance": "Outstanding Balance",

        "reports": "Generate Reports",

        "logout": "Logout",

        # ---------------- Dashboard ----------------

        "total_customers": "Total Customers",

        "total_credit": "Total Credit",

        "today_collection": "Today's Collection",

        "pending_amount": "Pending Amount",

        # ---------------- Customer ----------------

        "customer_id": "Customer ID",

        "customer_name": "Customer Name",

        "mobile": "Mobile Number",

        "address": "Address",

        "email": "Email",

        # ---------------- Credit Item ----------------

        "item_name": "Item Name",

        "quantity": "Quantity",

        "price": "Price",

        # ---------------- Payment ----------------

        "payment_id": "Payment ID",

        "payment_date": "Payment Date",

        "payment_amount": "Payment Amount",

        # ---------------- Transaction ----------------

        "transaction_id": "Transaction ID",

        "transaction_date": "Transaction Date",

        # ---------------- Buttons ----------------

        "add": "Add",

        "update": "Update",

        "delete": "Delete",

        "save": "Save",

        "cancel": "Cancel",

        "submit": "Submit",

        "search_btn": "Search",

        "back": "Back",

        "print": "Print",

        # ---------------- Messages ----------------

        "success": "Operation Completed Successfully",

        "failed": "Operation Failed",

        "record_saved": "Record Saved Successfully",

        "record_deleted": "Record Deleted Successfully",

        "no_data": "No Data Found",

        # ---------------- Reports ----------------

        "report_title": "Customer Credit Report",

        "customer_report": "Customer Report",

        "payment_report": "Payment Report",

        "transaction_report": "Transaction Report",

        "outstanding_report": "Outstanding Balance Report",

        "report_date": "Report Date",

        "generated_by": "Generated By",

        "total_due": "Total Due",

        "grand_total": "Grand Total",

    },

    # ======================================================
    # HINDI
    # ======================================================

    "हिन्दी": {

        # ---------------- Login ----------------

        "login": "लॉगिन करें",

        "login_as": "लॉगिन प्रकार",

        "shopkeeper": "दुकानदार",

        "employee": "कर्मचारी",

        "username": "उपयोगकर्ता नाम",

        "password": "पासवर्ड",

        "remember_me": "मुझे याद रखें",

        "forgot_password": "पासवर्ड भूल गए?",

        "welcome": "स्वागत है",

        "welcome_back": "वापसी पर स्वागत है",

        "invalid_login": "अमान्य उपयोगकर्ता नाम या पासवर्ड",

        # ---------------- Language ----------------

        "select_language": "भाषा चुनें",

        "continue": "आगे बढ़ें",

        # ---------------- Header ----------------

        "app_name": "उधार प्रबंधन प्रणाली",

        "search": "ग्राहक, भुगतान या लेन-देन खोजें...",

        "dark_mode": "डार्क मोड",

        # ---------------- Sidebar ----------------

        "dashboard": "डैशबोर्ड",

        "customers": "ग्राहक",

        "add_customer": "ग्राहक जोड़ें",

        "view_customers": "सभी ग्राहक",

        "update_customer": "ग्राहक अपडेट करें",

        "customer_performance": "ग्राहक प्रदर्शन",
        # ---------------- Credit Items ----------------

        "credit_items": "उधार वस्तुएँ",

        "add_credit_item": "उधार वस्तु जोड़ें",

        "view_credit_items": "सभी उधार वस्तुएँ",

        "update_credit_item": "उधार वस्तु अपडेट करें",

        # ---------------- Payments ----------------

        "payments": "भुगतान",

        "add_payment": "भुगतान जोड़ें",

        "view_payments": "सभी भुगतान",

        "update_payment": "भुगतान अपडेट करें",

        # ---------------- Credit Transactions ----------------

        "credit_transactions": "उधार लेन-देन",

        "add_transaction": "लेन-देन जोड़ें",

        "view_transactions": "सभी लेन-देन",

        "update_transaction": "लेन-देन अपडेट करें",

        # ---------------- Outstanding ----------------

        "outstanding_balance": "बकाया राशि",

        # ---------------- Reports ----------------

        "reports": "रिपोर्ट बनाएँ",

        "report_title": "ग्राहक उधार रिपोर्ट",

        "customer_report": "ग्राहक रिपोर्ट",

        "payment_report": "भुगतान रिपोर्ट",

        "transaction_report": "लेन-देन रिपोर्ट",

        "outstanding_report": "बकाया राशि रिपोर्ट",

        "report_date": "रिपोर्ट दिनांक",

        "generated_by": "द्वारा तैयार",

        "total_due": "कुल बकाया",

        "grand_total": "कुल योग",

        # ---------------- Customer ----------------

        "customer_id": "ग्राहक आईडी",

        "customer_name": "ग्राहक नाम",

        "mobile": "मोबाइल नंबर",

        "address": "पता",

        "email": "ईमेल",

        # ---------------- Credit Item ----------------

        "item_name": "वस्तु का नाम",

        "quantity": "मात्रा",

        "price": "कीमत",

        # ---------------- Payment ----------------

        "payment_id": "भुगतान आईडी",

        "payment_date": "भुगतान तिथि",

        "payment_amount": "भुगतान राशि",

        # ---------------- Transaction ----------------

        "transaction_id": "लेन-देन आईडी",

        "transaction_date": "लेन-देन तिथि",

        # ---------------- Buttons ----------------

        "add": "जोड़ें",

        "update": "अपडेट करें",

        "delete": "हटाएँ",

        "save": "सहेजें",

        "cancel": "रद्द करें",

        "submit": "सबमिट करें",

        "search_btn": "खोजें",

        "back": "वापस",

        "print": "प्रिंट",

        # ---------------- Messages ----------------

        "success": "कार्य सफलतापूर्वक पूरा हुआ",

        "failed": "कार्य असफल रहा",

        "record_saved": "रिकॉर्ड सफलतापूर्वक सहेजा गया",

        "record_deleted": "रिकॉर्ड सफलतापूर्वक हटाया गया",

        "no_data": "कोई डेटा उपलब्ध नहीं",

        "logout": "लॉगआउट",

    },

    # ======================================================
    # MARATHI
    # ======================================================

    "मराठी": {

        # ---------------- Login ----------------

        "login": "लॉगिन करा",

        "login_as": "लॉगिन प्रकार",

        "shopkeeper": "दुकानदार",

        "employee": "कर्मचारी",

        "username": "वापरकर्ता नाव",

        "password": "पासवर्ड",

        "remember_me": "मला लक्षात ठेवा",

        "forgot_password": "पासवर्ड विसरलात?",

        "welcome": "स्वागत आहे",

        "welcome_back": "पुन्हा स्वागत आहे",

        "invalid_login": "चुकीचे वापरकर्तानाव किंवा पासवर्ड",

        # ---------------- Language ----------------

        "select_language": "भाषा निवडा",

        "continue": "पुढे जा",

        # ---------------- Header ----------------

        "app_name": "उधार व्यवस्थापन प्रणाली",

        "search": "ग्राहक, पेमेंट, व्यवहार शोधा...",

        "dark_mode": "डार्क मोड",

        # ---------------- Sidebar ----------------

        "dashboard": "डॅशबोर्ड",

        "customers": "ग्राहक",

        "add_customer": "ग्राहक जोडा",

        "view_customers": "सर्व ग्राहक",

        "update_customer": "ग्राहक अद्यतनित करा",

        "customer_performance": "ग्राहक कामगिरी",

        "credit_items": "उधारी वस्तू",

        "add_credit_item": "उधारी वस्तू जोडा",

        "view_credit_items": "सर्व उधारी वस्तू",

        "update_credit_item": "उधारी वस्तू अद्यतनित करा",
        # ---------------- Payments ----------------

        "payments": "देयके",

        "add_payment": "देयक जोडा",

        "view_payments": "सर्व देयके",

        "update_payment": "देयक अद्यतनित करा",

        # ---------------- Credit Transactions ----------------

        "credit_transactions": "उधारी व्यवहार",

        "add_transaction": "व्यवहार जोडा",

        "view_transactions": "सर्व व्यवहार",

        "update_transaction": "व्यवहार अद्यतनित करा",

        # ---------------- Outstanding ----------------

        "outstanding_balance": "बाकी रक्कम",

        # ---------------- Reports ----------------

        "reports": "अहवाल तयार करा",

        "report_title": "ग्राहक उधारी अहवाल",

        "customer_report": "ग्राहक अहवाल",

        "payment_report": "देयक अहवाल",

        "transaction_report": "व्यवहार अहवाल",

        "outstanding_report": "बाकी रक्कम अहवाल",

        "report_date": "अहवाल दिनांक",

        "generated_by": "तयार करणारे",

        "total_due": "एकूण बाकी",

        "grand_total": "एकूण रक्कम",

        # ---------------- Customer ----------------

        "customer_id": "ग्राहक आयडी",

        "customer_name": "ग्राहकाचे नाव",

        "mobile": "मोबाईल क्रमांक",

        "address": "पत्ता",

        "email": "ईमेल",

        # ---------------- Credit Item ----------------

        "item_name": "वस्तूचे नाव",

        "quantity": "प्रमाण",

        "price": "किंमत",

        # ---------------- Payment ----------------

        "payment_id": "देयक आयडी",

        "payment_date": "देयक दिनांक",

        "payment_amount": "देयक रक्कम",

        # ---------------- Transaction ----------------

        "transaction_id": "व्यवहार आयडी",

        "transaction_date": "व्यवहार दिनांक",

        # ---------------- Buttons ----------------

        "add": "जोडा",

        "update": "अद्यतनित करा",

        "delete": "हटवा",

        "save": "जतन करा",

        "cancel": "रद्द करा",

        "submit": "सबमिट करा",

        "search_btn": "शोधा",

        "back": "मागे",

        "print": "प्रिंट",

        # ---------------- Messages ----------------

        "success": "कार्य यशस्वीरित्या पूर्ण झाले",

        "failed": "कार्य अयशस्वी झाले",

        "record_saved": "नोंद यशस्वीरित्या जतन झाली",

        "record_deleted": "नोंद यशस्वीरित्या हटवली",

        "no_data": "माहिती उपलब्ध नाही",

        "logout": "लॉगआउट",

    },
    # ======================================================
    # MALWARI
    # ======================================================
 
    "Malwari": {

        # ---------------- Login ----------------

        "login": "लॉग इन करो",
        "login_as": "ईं रूप में लॉग इन करो",
        "shopkeeper": "दुकानदार",
        "employee": "कमकर / नौकर",
        "username": "उपयोगकर्ता को नाम",
        "password": "पासवर्ड",
        "remember_me": "म्हाने याद राखो",
        "forgot_password": "पासवर्ड भूल ग्या?",
        "welcome": "घणो स्वागत है",
        "welcome_back": "पाछो स्वागत है",
        "invalid_login": "गलत उपयोगकर्ता नाम या पासवर्ड",

        # ---------------- Language ----------------

        "select_language": "भासा चुनो",
        "continue": "आगै बढ़ो",

        # ---------------- Header ----------------

        "app_name": "उधार खाता प्रबंधन प्रणाली",
        "search": "ग्राहक, भुगतान अर लेन-देन खोजो...",
        "dark_mode": "डार्क मोड",

        # ---------------- Sidebar ----------------

        "dashboard": "डैशबोर्ड",
        "customers": "ग्राहक",
        "add_customer": "नयो ग्राहक जोड़ो",
        "view_customers": "सगळा ग्राहक",
        "update_customer": "ग्राहक सुधारे करो",
        "customer_performance": "ग्राहक को व्यवहार",

        "credit_items": "उधार की चीजां",
        "add_credit_item": "उधार की चीज जोड़ो",
        "view_credit_items": "सगळी उधार की चीजां",
        "update_credit_item": "उधार की चीज सुधारे करो",

        # ---------------- Payments ----------------

        "payments": "भुगतान / जमा",
        "add_payment": "भुगतान जोड़ो",
        "view_payments": "सगळा भुगतान",
        "update_payment": "भुगतान सुधारे करो",

        # ---------------- Credit Transactions ----------------

        "credit_transactions": "उधार लेन-देन",
        "add_transaction": "लेन-देन जोड़ो",
        "view_transactions": "सगळा लेन-देन",
        "update_transaction": "लेन-देन सुधारे करो",

        # ---------------- Outstanding ----------------

        "outstanding_balance": "बाकी री रकम",

        # ---------------- Reports ----------------

        "reports": "रिपोर्ट बणाओ",
        "report_title": "ग्राहक उधार रिपोर्ट",
        "customer_report": "ग्राहक रिपोर्ट",
        "payment_report": "भुगतान रिपोर्ट",
        "transaction_report": "लेन-देन रिपोर्ट",
        "outstanding_report": "बाकी रकम री रिपोर्ट",
        "report_date": "रिपोर्ट री तारीख",
        "generated_by": "इण रे द्वारा बणायी गयी",
        "total_due": "कुल बाकी",
        "grand_total": "कुल योग",

        # ---------------- Customer ----------------

        "customer_id": "ग्राहक आईडी",
        "customer_name": "ग्राहक को नाम",
        "mobile": "मोबाइल नंबर",
        "address": "पतो",
        "email": "ईमेल",

        # ---------------- Credit Item ----------------

        "item_name": "चीज को नाम",
        "quantity": "मात्रा",
        "price": "कीमत",

        # ---------------- Payment ----------------

        "payment_id": "भुगतान आईडी",
        "payment_date": "भुगतान री तारीख",
        "payment_amount": "भुगतान री राशि",

        # ---------------- Transaction ----------------

        "transaction_id": "लेन-देन आईडी",
        "transaction_date": "लेन-देन री तारीख",

        # ---------------- Buttons ----------------

        "add": "जोड़ो",
        "update": "सुधारे करो",
        "delete": "हटाओ",
        "save": "सहेजो",
        "cancel": "रद्द करो",
        "submit": "जमा करो",
        "search_btn": "खोजो",
        "back": "पाछो",
        "print": "छापो",

        # ---------------- Messages ----------------

        "success": "काम सफल रह्यो",
        "failed": "काम असफल रह्यो",
        "record_saved": "रिकॉर्ड सही तरीक़ा सूं सहेज दियो",
        "record_deleted": "रिकॉर्ड सही तरीक़ा सूं हटा दियो",
        "no_data": "कोई जानकारी कोनी मिली",
        "logout": "लॉगआउट करो",

    },

}
# ======================================================
# Helper Function
# ======================================================

def get_language(language_name):
    return languages.get(language_name, languages["English"])


# ======================================================
# Language Selection Page
# ======================================================

def language_page(page, on_language_selected):

    # Default UI language (English)
    ui = get_language("English")

    language = ft.Dropdown(
        label=ui["select_language"],
        value="English",
        width=320,
        border_radius=10,
        options=[
            ft.dropdown.Option("English"),
            ft.dropdown.Option("हिन्दी"),
            ft.dropdown.Option("Malwari"),
            ft.dropdown.Option("मराठी"),
        ],
    )

    title = ft.Text(
        ui["app_name"],
        size=28,
        weight=ft.FontWeight.BOLD,
        text_align=ft.TextAlign.CENTER,
    )

    subtitle = ft.Text(
        "Choose Your Preferred Language",
        size=16,
        color=ft.Colors.GREY_700,
        text_align=ft.TextAlign.CENTER,
    )

    continue_btn = ft.ElevatedButton(
        text=ui["continue"],
        width=180,
        height=45,
        icon=ft.Icons.ARROW_FORWARD,
        style=ft.ButtonStyle(
            shape=ft.RoundedRectangleBorder(radius=10)
        ),
    )

    # Update UI when language changes
    def language_changed(e):
        lang = get_language(language.value)

        language.label = lang["select_language"]
        title.value = lang["app_name"]
        continue_btn.text = lang["continue"]

        # Language selection subtitle
        subtitles = {
            "English": "Choose Your Preferred Language",
            "हिन्दी": "अपनी पसंदीदा भाषा चुनें",
            "मराठी": "तुमची पसंतीची भाषा निवडा",
            "Malwari": "अपणी पसांदी री भासा चुनो",
        }

        subtitle.value = subtitles.get(language.value, "Choose Your Preferred Language")

        page.update()

    language.on_change = language_changed

    def continue_click(e):
        on_language_selected(language.value)

    continue_btn.on_click = continue_click

    return ft.Container(
        expand=True,
        alignment=ft.alignment.center,
        content=ft.Card(
            elevation=8,
            content=ft.Container(
                width=420,
                padding=30,
                content=ft.Column(
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                    spacing=20,
                    controls=[
                        ft.Icon(
                            ft.Icons.LANGUAGE,
                            size=80,
                            color=ft.Colors.BLUE,
                        ),
                        title,
                        subtitle,
                        language,
                        continue_btn,
                    ],
                ),
            ),
        ),
    )